<?php

/**
 * BaseMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $parent_id
 * @property integer $block_id
 * @property varchar $alias
 * @property enum $type
 * @property integer $s_order
 * @property Page $Page
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method integer getParentId()  Returns the current record's "parent_id" value
 * @method integer getBlockId()   Returns the current record's "block_id" value
 * @method varchar getAlias()     Returns the current record's "alias" value
 * @method enum    getType()      Returns the current record's "type" value
 * @method integer getSOrder()    Returns the current record's "s_order" value
 * @method Page    getPage()      Returns the current record's "Page" value
 * @method Menu    setId()        Sets the current record's "id" value
 * @method Menu    setParentId()  Sets the current record's "parent_id" value
 * @method Menu    setBlockId()   Sets the current record's "block_id" value
 * @method Menu    setAlias()     Sets the current record's "alias" value
 * @method Menu    setType()      Sets the current record's "type" value
 * @method Menu    setSOrder()    Sets the current record's "s_order" value
 * @method Menu    setPage()      Sets the current record's "Page" value
 * 
 * @package    sft.loc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menu');
        $this->hasColumn('id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('parent_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('block_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('alias', 'varchar', 255, array(
             'type' => 'varchar',
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('type', 'enum', 10, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'horizontal',
              1 => 'vertical',
             ),
             'default' => 'horizontal',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('s_order', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));


        $this->index('menu_parent_id', array(
             'fields' => 
             array(
              0 => 'parent_id',
             ),
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Page', array(
             'local' => 'block_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}