<?php

/**
 * BaseText
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $block_id
 * @property clob $content
 * @property Block $Block
 * 
 * @method integer getId()       Returns the current record's "id" value
 * @method integer getBlockId()  Returns the current record's "block_id" value
 * @method clob    getContent()  Returns the current record's "content" value
 * @method Block   getBlock()    Returns the current record's "Block" value
 * @method Text    setId()       Sets the current record's "id" value
 * @method Text    setBlockId()  Sets the current record's "block_id" value
 * @method Text    setContent()  Sets the current record's "content" value
 * @method Text    setBlock()    Sets the current record's "Block" value
 * 
 * @package    sft.loc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseText extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('text');
        $this->hasColumn('id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('block_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             'default' => '',
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Block', array(
             'local' => 'block_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}