<?php

/**
 * BaseBlockLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $block_id
 * @property integer $entity_id
 * @property integer $s_order
 * @property Block $Block
 * 
 * @method integer   getId()        Returns the current record's "id" value
 * @method integer   getBlockId()   Returns the current record's "block_id" value
 * @method integer   getEntityId()  Returns the current record's "entity_id" value
 * @method integer   getSOrder()    Returns the current record's "s_order" value
 * @method Block     getBlock()     Returns the current record's "Block" value
 * @method BlockLink setId()        Sets the current record's "id" value
 * @method BlockLink setBlockId()   Sets the current record's "block_id" value
 * @method BlockLink setEntityId()  Sets the current record's "entity_id" value
 * @method BlockLink setSOrder()    Sets the current record's "s_order" value
 * @method BlockLink setBlock()     Sets the current record's "Block" value
 * 
 * @package    sft.loc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlockLink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('block_link');
        $this->hasColumn('id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('block_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('entity_id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 5,
             ));
        $this->hasColumn('s_order', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => 0,
             'length' => 5,
             ));


        $this->index('block_link_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Block', array(
             'local' => 'block_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}