<?php

/**
 * BaseCapcha
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $picture
 * @property string $value
 * 
 * @method integer getId()      Returns the current record's "id" value
 * @method string  getPicture() Returns the current record's "picture" value
 * @method string  getValue()   Returns the current record's "value" value
 * @method Capcha  setId()      Sets the current record's "id" value
 * @method Capcha  setPicture() Sets the current record's "picture" value
 * @method Capcha  setValue()   Sets the current record's "value" value
 * 
 * @package    sft.loc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCapcha extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('capcha');
        $this->hasColumn('id', 'integer', 5, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('picture', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('value', 'string', 10, array(
             'type' => 'string',
             'default' => '',
             'length' => 10,
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}