<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/01/24 22:14:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sft.loc',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
