<?php

/**
 * Block
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sft.loc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Block extends BaseBlock
{
    const TYPE_TEXT = 'text';
    const TYPE_MEDIA = 'media';
    const TYPE_TEXT_LIST = 'text_list';
    const TYPE_MEDIA_LIST = 'media_list';
    const TYPE_MENU = 'menu';
    const TYPE_SEARCH = 'search';
    const TYPE_TEXT_LIST_LINK = 'text_list_link';
    const TYPE_MEDIA_LINK = 'media_link';


    public function preSave($event)
    {
        if ($this->getParentId() == 0) {
            $this->setParentId(null);
        }

        return parent::preSave($event);
    }


    public function getEncodeHeader()
    {
        return Tools::urlencode($this->getHeader());
    }


    public function getInstance()
    {
        $instance = null;
        switch ($this->getType()) {
            case 'text_list' :      $instance = Doctrine_Core::getTable('TextList');    break;
            case 'text' :           $instance = Doctrine_Core::getTable('Text');        break;
            case 'media' :          $instance = Doctrine_Core::getTable('Media');       break;
            case 'search' :         $instance = Doctrine_Core::getTable('Search');      break;
            case 'menu' :           $instance = Doctrine_Core::getTable('Menu');        break;
            case 'text_list_link' : $instance = Doctrine_Core::getTable('TextList');    break;
            case 'media_link' :     $instance = Doctrine_Core::getTable('Media');       break;
        }
        $instance->setBlock($this);

        return $instance;
    }


    public function getTemplateName()
    {
        return $this->getType();
    }


    public function getDecodedCss()
    {
        $css = new Css();
        $css->decode($this->getCss());
        return $css;
    }


    public function getContent($id = null)
    {
        return $this->getInstance()->getContent($id);
    }


    public function getChilds()
    {
        return Doctrine_Core::getTable('Block')->getChilds($this->getPageId(), $this->getId());
    }


    public function hasChilds()
    {
        $childs = $this->getChilds();
        return count($childs);
    }

}
