<?php

/**
 * BlockLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlockLinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlockLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlockLink');
    }
}