<?php

/**
 * CapchaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CapchaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CapchaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Capcha');
    }
}