<?php

/**
 * Media
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sft.loc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Media extends BaseMedia
{
    /**
     * Substitute field 'header' instead 'filename'
     * in order to save persistence in templates
     *
     * @return varchar
     */
    public function getHeader()
    {
        return $this->getFilename();
    }
}
