<?php

/**
 * PageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PageTable extends Doctrine_Table
{
    const INDEX_PAGE_TYPE = 'index';

    /**
     * Returns an instance of this class.
     *
     * @return object PageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Page');
    }


    public function getIndexPage()
    {
        $indexPage = $this->findOneBy('type', self::INDEX_PAGE_TYPE);

        if (!$indexPage->getData()) {
            throw new Doctrine_Exception('Index page is absent');
        }

        return $indexPage;
    }
}