# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css]

  javascripts:
    - http://code.jquery.com/jquery-1.9.0.js
    - http://documentcloud.github.com/underscore/underscore-min.js
    - https://raw.github.com/douglascrockford/JSON-js/master/json2.js
    - http://backbonejs.ru/backbone-min.js

  has_layout:     true
  layout:         layout
