generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Media
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          media
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [filename, filepath, mimetype, filesize, visible]
      filter:
        display: [filename, filepath, mimetype, filesize, visible]
      form:    ~
      edit:    ~
      new:     ~
