generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Block
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          block
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Block Management
        display: [=header, type, css, visible]
        layout: stacked
        params: |
          <div class="row">
          Block %%header%% on the %%page%%<br />
          <span class="status">Type: %%type%%</span><br>
          <div class="clear"></div>
          <span class="status">Is visible: %%visible%%</span><br>
          <span class="timestamp">Created at %%created_at%%</span>
          </div>
      filter:
        display: [header, type, visible]
      form:    ~
      edit:    ~
      new:     ~
