<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/01/27 16:44:28
sfConfig::add(array(
  'app_default_header' => 'sft',
  'app_default_meta_keywords' => 'sft keywords',
  'app_default_meta_description' => 'sft description',
  'app_default_meta_indexing' => 1,
));
