<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/24 00:12:55

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=sft',
  'username' => 'sft',
  'password' => '1',
  'attributes' => 
  array (
    'use_native_enum' => true,
  ),
  'name' => 'doctrine',
)),);
