<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/03 20:06:28

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=sft',
  'username' => 'sft',
  'password' => '1',
  'attributes' => 
  array (
    'use_native_enum' => true,
  ),
  'name' => 'doctrine',
)),);
